
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 839071
	#The name of the modpack
	modpackName = "Medieval Immersed - Mayhem Edition -"
	#The version of the modpack
	modpackVersion = "v.011"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

